
package eperpus;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 *
 * @author NRSS
 */
public class Anggota extends javax.swing.JFrame {
private static Connection koneksi; //Koneksi
   
   
/**
     * Creates new form Anggota
     */
//tampil tabel
public void tampilkandata() {
    
        DefaultTableModel tabelanggota = new DefaultTableModel();
        tabelanggota.addColumn("Id");
        tabelanggota.addColumn("Nama");
        tabelanggota.addColumn("Alamat");
        tabelanggota.addColumn("Tanggal Lahir");
        tabelanggota.addColumn("Jenis Kelamin");
        try {
            buka_koneksi();
            String sql = "select * from anggota";
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelanggota.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
           tblAnggota.setModel(tabelanggota);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+e.getMessage());
        }

    }

    public Anggota() {
        initComponents();
         this.setLocationRelativeTo(this);
    }
    //koneksi
private static Connection buka_koneksi() {
    
        if (koneksi==null) {
            try {
                String url="jdbc:mysql://localhost:3306/eperpus"; 
                String user="root"; //user mysql
                String password=""; //password mysql
               
                koneksi=DriverManager.getConnection(url,user,password);
                
            }catch (SQLException t) {
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan "+t.getMessage());
            }
        }
     return koneksi;
     
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenuBar13 = new javax.swing.JMenuBar();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenuBar14 = new javax.swing.JMenuBar();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenuBar15 = new javax.swing.JMenuBar();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenuBar16 = new javax.swing.JMenuBar();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenuBar17 = new javax.swing.JMenuBar();
        jMenu37 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenuBar18 = new javax.swing.JMenuBar();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenuBar19 = new javax.swing.JMenuBar();
        jMenu41 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenuBar20 = new javax.swing.JMenuBar();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenuBar21 = new javax.swing.JMenuBar();
        jMenu45 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenuBar22 = new javax.swing.JMenuBar();
        jMenu47 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenuBar23 = new javax.swing.JMenuBar();
        jMenu49 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenuBar24 = new javax.swing.JMenuBar();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenuBar25 = new javax.swing.JMenuBar();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenuBar26 = new javax.swing.JMenuBar();
        jMenu55 = new javax.swing.JMenu();
        jMenu56 = new javax.swing.JMenu();
        jMenuBar27 = new javax.swing.JMenuBar();
        jMenu57 = new javax.swing.JMenu();
        jMenu58 = new javax.swing.JMenu();
        jMenuBar28 = new javax.swing.JMenuBar();
        jMenu59 = new javax.swing.JMenu();
        jMenu60 = new javax.swing.JMenu();
        jMenuBar29 = new javax.swing.JMenuBar();
        jMenu61 = new javax.swing.JMenu();
        jMenu62 = new javax.swing.JMenu();
        jMenuBar30 = new javax.swing.JMenuBar();
        jMenu63 = new javax.swing.JMenu();
        jMenu64 = new javax.swing.JMenu();
        jMenuBar31 = new javax.swing.JMenuBar();
        jMenu65 = new javax.swing.JMenu();
        jMenu66 = new javax.swing.JMenu();
        jMenu67 = new javax.swing.JMenu();
        jMenuBar32 = new javax.swing.JMenuBar();
        jMenu68 = new javax.swing.JMenu();
        jMenu69 = new javax.swing.JMenu();
        jMenuBar33 = new javax.swing.JMenuBar();
        jMenu70 = new javax.swing.JMenu();
        jMenu71 = new javax.swing.JMenu();
        jMenuBar34 = new javax.swing.JMenuBar();
        jMenu72 = new javax.swing.JMenu();
        jMenu73 = new javax.swing.JMenu();
        jMenuBar35 = new javax.swing.JMenuBar();
        jMenu74 = new javax.swing.JMenu();
        jMenu75 = new javax.swing.JMenu();
        jMenuBar36 = new javax.swing.JMenuBar();
        jMenu76 = new javax.swing.JMenu();
        jMenu77 = new javax.swing.JMenu();
        jMenuBar37 = new javax.swing.JMenuBar();
        jMenu78 = new javax.swing.JMenu();
        jMenu79 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu80 = new javax.swing.JMenu();
        jMenuBar38 = new javax.swing.JMenuBar();
        jMenu81 = new javax.swing.JMenu();
        jMenu82 = new javax.swing.JMenu();
        jMenuBar39 = new javax.swing.JMenuBar();
        jMenu83 = new javax.swing.JMenu();
        jMenu84 = new javax.swing.JMenu();
        jMenuBar40 = new javax.swing.JMenuBar();
        jMenu85 = new javax.swing.JMenu();
        jMenu86 = new javax.swing.JMenu();
        jMenuBar41 = new javax.swing.JMenuBar();
        jMenu87 = new javax.swing.JMenu();
        jMenu88 = new javax.swing.JMenu();
        jMenuBar42 = new javax.swing.JMenuBar();
        jMenu89 = new javax.swing.JMenu();
        jMenu90 = new javax.swing.JMenu();
        jMenuBar43 = new javax.swing.JMenuBar();
        jMenu91 = new javax.swing.JMenu();
        jMenu92 = new javax.swing.JMenu();
        jMenuBar44 = new javax.swing.JMenuBar();
        jMenu93 = new javax.swing.JMenu();
        jMenu94 = new javax.swing.JMenu();
        jMenuBar45 = new javax.swing.JMenuBar();
        jMenu95 = new javax.swing.JMenu();
        jMenu96 = new javax.swing.JMenu();
        jMenuBar46 = new javax.swing.JMenuBar();
        jMenu97 = new javax.swing.JMenu();
        jMenu98 = new javax.swing.JMenu();
        jMenuBar47 = new javax.swing.JMenuBar();
        jMenu99 = new javax.swing.JMenu();
        jMenu100 = new javax.swing.JMenu();
        jMenuBar48 = new javax.swing.JMenuBar();
        jMenu101 = new javax.swing.JMenu();
        jMenu102 = new javax.swing.JMenu();
        jMenuBar49 = new javax.swing.JMenuBar();
        jMenu103 = new javax.swing.JMenu();
        jMenu104 = new javax.swing.JMenu();
        jMenuBar50 = new javax.swing.JMenuBar();
        jMenu105 = new javax.swing.JMenu();
        jMenu106 = new javax.swing.JMenu();
        jMenuBar51 = new javax.swing.JMenuBar();
        jMenu107 = new javax.swing.JMenu();
        jMenu108 = new javax.swing.JMenu();
        jMenuBar52 = new javax.swing.JMenuBar();
        jMenu109 = new javax.swing.JMenu();
        jMenu110 = new javax.swing.JMenu();
        jMenuBar53 = new javax.swing.JMenuBar();
        jMenu111 = new javax.swing.JMenu();
        jMenu112 = new javax.swing.JMenu();
        jMenuBar54 = new javax.swing.JMenuBar();
        jMenu113 = new javax.swing.JMenu();
        jMenu114 = new javax.swing.JMenu();
        jMenuBar55 = new javax.swing.JMenuBar();
        jMenu115 = new javax.swing.JMenu();
        jMenu116 = new javax.swing.JMenu();
        jMenuBar56 = new javax.swing.JMenuBar();
        jMenu117 = new javax.swing.JMenu();
        jMenu118 = new javax.swing.JMenu();
        jMenuBar57 = new javax.swing.JMenuBar();
        jMenu119 = new javax.swing.JMenu();
        jMenu120 = new javax.swing.JMenu();
        jMenuBar58 = new javax.swing.JMenuBar();
        jMenu121 = new javax.swing.JMenu();
        jMenu122 = new javax.swing.JMenu();
        jMenuBar59 = new javax.swing.JMenuBar();
        jMenu123 = new javax.swing.JMenu();
        jMenu124 = new javax.swing.JMenu();
        jMenuBar60 = new javax.swing.JMenuBar();
        jMenu125 = new javax.swing.JMenu();
        jMenu126 = new javax.swing.JMenu();
        jMenu128 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu127 = new javax.swing.JMenu();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        pnlAnggota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTtl = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnggota = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mniAnggota = new javax.swing.JMenuItem();
        mniKoleksi = new javax.swing.JMenuItem();
        mniPinjam = new javax.swing.JMenuItem();
        mniUtama = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniSimpan = new javax.swing.JMenuItem();
        mniEdit = new javax.swing.JMenuItem();
        mniCari = new javax.swing.JMenuItem();
        mniHapus = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu7.setText("jMenu7");

        jMenuItem3.setText("jMenuItem3");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenuItem4.setText("jMenuItem4");

        jMenu10.setText("jMenu10");

        jMenu2.setText("File");
        jMenuBar3.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar3.add(jMenu3);

        jMenu11.setText("File");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar4.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar5.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar5.add(jMenu14);

        jMenu15.setText("File");
        jMenuBar6.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar6.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar7.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar7.add(jMenu18);

        jMenu19.setText("File");
        jMenuBar8.add(jMenu19);

        jMenu20.setText("Edit");
        jMenuBar8.add(jMenu20);

        jMenu21.setText("File");
        jMenuBar9.add(jMenu21);

        jMenu22.setText("Edit");
        jMenuBar9.add(jMenu22);

        jMenu23.setText("File");
        jMenuBar10.add(jMenu23);

        jMenu24.setText("Edit");
        jMenuBar10.add(jMenu24);

        jMenu25.setText("File");
        jMenuBar11.add(jMenu25);

        jMenu26.setText("Edit");
        jMenuBar11.add(jMenu26);

        jMenu27.setText("File");
        jMenuBar12.add(jMenu27);

        jMenu28.setText("Edit");
        jMenuBar12.add(jMenu28);

        jMenu29.setText("File");
        jMenuBar13.add(jMenu29);

        jMenu30.setText("Edit");
        jMenuBar13.add(jMenu30);

        jMenu31.setText("File");
        jMenuBar14.add(jMenu31);

        jMenu32.setText("Edit");
        jMenuBar14.add(jMenu32);

        jMenu33.setText("File");
        jMenuBar15.add(jMenu33);

        jMenu34.setText("Edit");
        jMenuBar15.add(jMenu34);

        jMenu35.setText("File");
        jMenuBar16.add(jMenu35);

        jMenu36.setText("Edit");
        jMenuBar16.add(jMenu36);

        jMenu37.setText("File");
        jMenuBar17.add(jMenu37);

        jMenu38.setText("Edit");
        jMenuBar17.add(jMenu38);

        jMenu39.setText("File");
        jMenuBar18.add(jMenu39);

        jMenu40.setText("Edit");
        jMenuBar18.add(jMenu40);

        jMenu41.setText("File");
        jMenuBar19.add(jMenu41);

        jMenu42.setText("Edit");
        jMenuBar19.add(jMenu42);

        jMenu43.setText("File");
        jMenuBar20.add(jMenu43);

        jMenu44.setText("Edit");
        jMenuBar20.add(jMenu44);

        jMenu45.setText("File");
        jMenuBar21.add(jMenu45);

        jMenu46.setText("Edit");
        jMenuBar21.add(jMenu46);

        jMenu47.setText("File");
        jMenuBar22.add(jMenu47);

        jMenu48.setText("Edit");
        jMenuBar22.add(jMenu48);

        jMenu49.setText("File");
        jMenuBar23.add(jMenu49);

        jMenu50.setText("Edit");
        jMenuBar23.add(jMenu50);

        jMenu51.setText("File");
        jMenuBar24.add(jMenu51);

        jMenu52.setText("Edit");
        jMenuBar24.add(jMenu52);

        jMenu53.setText("File");
        jMenuBar25.add(jMenu53);

        jMenu54.setText("Edit");
        jMenuBar25.add(jMenu54);

        jMenu55.setText("File");
        jMenuBar26.add(jMenu55);

        jMenu56.setText("Edit");
        jMenuBar26.add(jMenu56);

        jMenu57.setText("File");
        jMenuBar27.add(jMenu57);

        jMenu58.setText("Edit");
        jMenuBar27.add(jMenu58);

        jMenu59.setText("File");
        jMenuBar28.add(jMenu59);

        jMenu60.setText("Edit");
        jMenuBar28.add(jMenu60);

        jMenu61.setText("File");
        jMenuBar29.add(jMenu61);

        jMenu62.setText("Edit");
        jMenuBar29.add(jMenu62);

        jMenu63.setText("File");
        jMenuBar30.add(jMenu63);

        jMenu64.setText("Edit");
        jMenuBar30.add(jMenu64);

        jMenu65.setText("File");
        jMenuBar31.add(jMenu65);

        jMenu66.setText("Edit");
        jMenuBar31.add(jMenu66);

        jMenu67.setText("jMenu67");

        jMenu68.setText("File");
        jMenuBar32.add(jMenu68);

        jMenu69.setText("Edit");
        jMenuBar32.add(jMenu69);

        jMenu70.setText("File");
        jMenuBar33.add(jMenu70);

        jMenu71.setText("Edit");
        jMenuBar33.add(jMenu71);

        jMenu72.setText("File");
        jMenuBar34.add(jMenu72);

        jMenu73.setText("Edit");
        jMenuBar34.add(jMenu73);

        jMenu74.setText("File");
        jMenuBar35.add(jMenu74);

        jMenu75.setText("Edit");
        jMenuBar35.add(jMenu75);

        jMenu76.setText("File");
        jMenuBar36.add(jMenu76);

        jMenu77.setText("Edit");
        jMenuBar36.add(jMenu77);

        jMenu78.setText("File");
        jMenuBar37.add(jMenu78);

        jMenu79.setText("Edit");
        jMenuBar37.add(jMenu79);

        jMenuItem5.setText("jMenuItem5");

        jMenu80.setText("jMenu80");

        jMenu81.setText("File");
        jMenuBar38.add(jMenu81);

        jMenu82.setText("Edit");
        jMenuBar38.add(jMenu82);

        jMenu83.setText("File");
        jMenuBar39.add(jMenu83);

        jMenu84.setText("Edit");
        jMenuBar39.add(jMenu84);

        jMenu85.setText("File");
        jMenuBar40.add(jMenu85);

        jMenu86.setText("Edit");
        jMenuBar40.add(jMenu86);

        jMenu87.setText("File");
        jMenuBar41.add(jMenu87);

        jMenu88.setText("Edit");
        jMenuBar41.add(jMenu88);

        jMenu89.setText("File");
        jMenuBar42.add(jMenu89);

        jMenu90.setText("Edit");
        jMenuBar42.add(jMenu90);

        jMenu91.setText("File");
        jMenuBar43.add(jMenu91);

        jMenu92.setText("Edit");
        jMenuBar43.add(jMenu92);

        jMenu93.setText("File");
        jMenuBar44.add(jMenu93);

        jMenu94.setText("Edit");
        jMenuBar44.add(jMenu94);

        jMenu95.setText("File");
        jMenuBar45.add(jMenu95);

        jMenu96.setText("Edit");
        jMenuBar45.add(jMenu96);

        jMenu97.setText("File");
        jMenuBar46.add(jMenu97);

        jMenu98.setText("Edit");
        jMenuBar46.add(jMenu98);

        jMenu99.setText("File");
        jMenuBar47.add(jMenu99);

        jMenu100.setText("Edit");
        jMenuBar47.add(jMenu100);

        jMenu101.setText("File");
        jMenuBar48.add(jMenu101);

        jMenu102.setText("Edit");
        jMenuBar48.add(jMenu102);

        jMenu103.setText("File");
        jMenuBar49.add(jMenu103);

        jMenu104.setText("Edit");
        jMenuBar49.add(jMenu104);

        jMenu105.setText("File");
        jMenuBar50.add(jMenu105);

        jMenu106.setText("Edit");
        jMenuBar50.add(jMenu106);

        jMenu107.setText("File");
        jMenuBar51.add(jMenu107);

        jMenu108.setText("Edit");
        jMenuBar51.add(jMenu108);

        jMenu109.setText("File");
        jMenuBar52.add(jMenu109);

        jMenu110.setText("Edit");
        jMenuBar52.add(jMenu110);

        jMenu111.setText("File");
        jMenuBar53.add(jMenu111);

        jMenu112.setText("Edit");
        jMenuBar53.add(jMenu112);

        jMenu113.setText("File");
        jMenuBar54.add(jMenu113);

        jMenu114.setText("Edit");
        jMenuBar54.add(jMenu114);

        jMenu115.setText("File");
        jMenuBar55.add(jMenu115);

        jMenu116.setText("Edit");
        jMenuBar55.add(jMenu116);

        jMenu117.setText("File");
        jMenuBar56.add(jMenu117);

        jMenu118.setText("Edit");
        jMenuBar56.add(jMenu118);

        jMenu119.setText("File");
        jMenuBar57.add(jMenu119);

        jMenu120.setText("Edit");
        jMenuBar57.add(jMenu120);

        jMenu121.setText("File");
        jMenuBar58.add(jMenu121);

        jMenu122.setText("Edit");
        jMenuBar58.add(jMenu122);

        jMenu123.setText("File");
        jMenuBar59.add(jMenu123);

        jMenu124.setText("Edit");
        jMenuBar59.add(jMenu124);

        jMenu125.setText("File");
        jMenuBar60.add(jMenu125);

        jMenu126.setText("Edit");
        jMenuBar60.add(jMenu126);

        jMenu128.setText("jMenu128");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenu127.setText("jMenu127");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-PERPUS");
        setAutoRequestFocus(false);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlAnggota.setBackground(new java.awt.Color(203, 180, 135));

        jLabel1.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel1.setText("ID Anggota");

        jLabel2.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel4.setText("TTL");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        txtId.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtNama.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtAlamat.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtTtl.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        cmbJenis.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));

        btnEdit.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lato Heavy", 0, 8)); // NOI18N
        jLabel7.setText("(YYYY-MM-DD)");

        jLabel8.setFont(new java.awt.Font("Lato Black", 1, 36)); // NOI18N
        jLabel8.setText("FORM ANGGOTA");

        tblAnggota.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N
        tblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "TTL", "Jenis Kelamin"
            }
        ));
        tblAnggota.setEnabled(false);
        jScrollPane2.setViewportView(tblAnggota);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo1.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Lato Heavy", 0, 8)); // NOI18N
        jLabel9.setText("(ID berupa angka)");

        javax.swing.GroupLayout pnlAnggotaLayout = new javax.swing.GroupLayout(pnlAnggota);
        pnlAnggota.setLayout(pnlAnggotaLayout);
        pnlAnggotaLayout.setHorizontalGroup(
            pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAnggotaLayout.createSequentialGroup()
                .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTtl, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(txtAlamat))
                                        .addGap(2, 2, 2))
                                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37))
                            .addGroup(pnlAnggotaLayout.createSequentialGroup()
                                .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        pnlAnggotaLayout.setVerticalGroup(
            pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnggotaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAnggotaLayout.createSequentialGroup()
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(pnlAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(100, 32769));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 70));
        jMenuBar1.setName(""); // NOI18N

        mnuMenu.setText("MENU");

        mniAnggota.setText("Anggota");
        mniAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAnggotaActionPerformed(evt);
            }
        });
        mnuMenu.add(mniAnggota);

        mniKoleksi.setText("Koleksi Buku");
        mniKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKoleksiActionPerformed(evt);
            }
        });
        mnuMenu.add(mniKoleksi);

        mniPinjam.setText("Peminjaman");
        mniPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPinjamActionPerformed(evt);
            }
        });
        mnuMenu.add(mniPinjam);

        mniUtama.setText("Utama");
        mniUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUtamaActionPerformed(evt);
            }
        });
        mnuMenu.add(mniUtama);

        jMenuBar1.add(mnuMenu);

        mnuHelp.setText("HELP");

        mniSimpan.setText("Simpan");
        mniSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSimpanActionPerformed(evt);
            }
        });
        mnuHelp.add(mniSimpan);

        mniEdit.setText("Edit");
        mniEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditActionPerformed(evt);
            }
        });
        mnuHelp.add(mniEdit);

        mniCari.setText("Cari");
        mniCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCariActionPerformed(evt);
            }
        });
        mnuHelp.add(mniCari);

        mniHapus.setText("Hapus");
        mniHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHapusActionPerformed(evt);
            }
        });
        mnuHelp.add(mniHapus);

        jMenuBar1.add(mnuHelp);

        mnuAbout.setText("ABOUT");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        if((txtId.getText().equals(""))||(txtNama.getText().equals(""))||(txtAlamat.getText().equals(""))||(txtTtl.getText().equals("")))
            {
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
            else 
            {
                Connection c=buka_koneksi(); //panggil function koneksi
         String sqlkode="Insert into anggota(id,nama,alamat,ttl,jkl) values ('"+this.txtId.getText()+"',"
                     + "'"+this.txtNama.getText()+"',"+ "'"+this.txtAlamat.getText()+"',"+"'"+this.txtTtl.getText()+"',"
                 +"'"+this.cmbJenis.getSelectedItem()+"')";
            try { //jalankan query tersebut
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               //tampilkan data
                tampilkandata();
                JOptionPane.showMessageDialog(this, "Simpan Berhasil","Informasi",1);
                cmbJenis.setSelectedItem("Laki-Laki");
                txtId.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
                txtTtl.setText("");
                
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
                
                txtId.requestFocus();
           
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
          }
          else{
            Connection c=buka_koneksi();
         String sqlkode="Delete from anggota "
                 + "Where id='"+this.txtId.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               cmbJenis.setSelectedItem("Laki-Laki");
               txtId.setText("");
               
               txtNama.setText("");
               txtAlamat.setText("");
               txtTtl.setText("");
               txtId.requestFocus();
               tampilkandata();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
          }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if((txtId.getText().equals(""))||(txtNama.getText().equals(""))||(txtAlamat.getText().equals(""))||(txtTtl.getText().equals("")))
            {
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
            else 
            { 
                Connection c=buka_koneksi();
            
        String sqlkode="Update anggota SET nama='"+this.txtNama.getText()+"'," + "alamat='"+this.txtAlamat.getText()+"',"
                +"ttl='"+this.txtTtl.getText()+"',"+"jkl='"+this.cmbJenis.getSelectedItem()+"'" 
                + "Where id='"+this.txtId.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               JOptionPane.showMessageDialog(this, "Edit Berhasil","Informasi",1);
               cmbJenis.setSelectedItem("Laki-Laki");
               txtId.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
                txtTtl.setText("");
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
                
                txtId.requestFocus();
           
               tampilkandata();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
            }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
          }
        else{
        DefaultTableModel tabelanggota = new DefaultTableModel();
        tabelanggota.addColumn("Id");
        tabelanggota.addColumn("Nama");
        tabelanggota.addColumn("Alamat");
        tabelanggota.addColumn("Tanggal Lahir");
        tabelanggota.addColumn("Jenis Kelamin");
        
        try {
            buka_koneksi();
            String sql = "Select * from anggota where id like '%" +txtId.getText()+
                    "%'" +"or nama like '%" + txtId.getText() + "%'"; 
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            
            cmbJenis.setSelectedItem("Laki-Laki");
            txtId.setText("");
            txtNama.setText("");
            txtAlamat.setText("");
            txtTtl.setText("");
            btnHapus.setEnabled(true);
            btnEdit.setEnabled(true);
            txtId.requestFocus();
            while (res.next()) {
                tabelanggota.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
           tblAnggota.setModel(tabelanggota);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan ");
        }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void mnuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Aplikasi ini dibuat untuk memudahkan admin untuk mendata anggota, inventaris buku, dan peminjaman buku perpustakaan."
                + "\nSemoga bermanfaat -NRSS"+"\n");
    }//GEN-LAST:event_mnuAboutMouseClicked

    private void mniUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUtamaActionPerformed
        // TODO add your handling code here:
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniUtamaActionPerformed

    private void mniPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPinjamActionPerformed
        // TODO add your handling code here:
        new Pinjam().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniPinjamActionPerformed

    private void mniKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKoleksiActionPerformed
        // TODO add your handling code here:
        new Koleksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniKoleksiActionPerformed

    private void mniAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAnggotaActionPerformed
        // TODO add your handling code here:
        new Anggota().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniAnggotaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampilkandata();
        txtId.requestFocus();
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_formWindowActivated

    private void mniSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSimpanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi semua kolom data agar dapat menyimpan data.");
    }//GEN-LAST:event_mniSimpanActionPerformed

    private void mniEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi ID anggota dan masukan semua data yang ingin diedit.");
    }//GEN-LAST:event_mniEditActionPerformed

    private void mniCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCariActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan ID anggota untuk mencari data."
                + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniCariActionPerformed

    private void mniHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHapusActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan ID anggota yang ingin dihapus."
                + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbJenis;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu100;
    private javax.swing.JMenu jMenu101;
    private javax.swing.JMenu jMenu102;
    private javax.swing.JMenu jMenu103;
    private javax.swing.JMenu jMenu104;
    private javax.swing.JMenu jMenu105;
    private javax.swing.JMenu jMenu106;
    private javax.swing.JMenu jMenu107;
    private javax.swing.JMenu jMenu108;
    private javax.swing.JMenu jMenu109;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu110;
    private javax.swing.JMenu jMenu111;
    private javax.swing.JMenu jMenu112;
    private javax.swing.JMenu jMenu113;
    private javax.swing.JMenu jMenu114;
    private javax.swing.JMenu jMenu115;
    private javax.swing.JMenu jMenu116;
    private javax.swing.JMenu jMenu117;
    private javax.swing.JMenu jMenu118;
    private javax.swing.JMenu jMenu119;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu120;
    private javax.swing.JMenu jMenu121;
    private javax.swing.JMenu jMenu122;
    private javax.swing.JMenu jMenu123;
    private javax.swing.JMenu jMenu124;
    private javax.swing.JMenu jMenu125;
    private javax.swing.JMenu jMenu126;
    private javax.swing.JMenu jMenu127;
    private javax.swing.JMenu jMenu128;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu55;
    private javax.swing.JMenu jMenu56;
    private javax.swing.JMenu jMenu57;
    private javax.swing.JMenu jMenu58;
    private javax.swing.JMenu jMenu59;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu60;
    private javax.swing.JMenu jMenu61;
    private javax.swing.JMenu jMenu62;
    private javax.swing.JMenu jMenu63;
    private javax.swing.JMenu jMenu64;
    private javax.swing.JMenu jMenu65;
    private javax.swing.JMenu jMenu66;
    private javax.swing.JMenu jMenu67;
    private javax.swing.JMenu jMenu68;
    private javax.swing.JMenu jMenu69;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu70;
    private javax.swing.JMenu jMenu71;
    private javax.swing.JMenu jMenu72;
    private javax.swing.JMenu jMenu73;
    private javax.swing.JMenu jMenu74;
    private javax.swing.JMenu jMenu75;
    private javax.swing.JMenu jMenu76;
    private javax.swing.JMenu jMenu77;
    private javax.swing.JMenu jMenu78;
    private javax.swing.JMenu jMenu79;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu80;
    private javax.swing.JMenu jMenu81;
    private javax.swing.JMenu jMenu82;
    private javax.swing.JMenu jMenu83;
    private javax.swing.JMenu jMenu84;
    private javax.swing.JMenu jMenu85;
    private javax.swing.JMenu jMenu86;
    private javax.swing.JMenu jMenu87;
    private javax.swing.JMenu jMenu88;
    private javax.swing.JMenu jMenu89;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenu90;
    private javax.swing.JMenu jMenu91;
    private javax.swing.JMenu jMenu92;
    private javax.swing.JMenu jMenu93;
    private javax.swing.JMenu jMenu94;
    private javax.swing.JMenu jMenu95;
    private javax.swing.JMenu jMenu96;
    private javax.swing.JMenu jMenu97;
    private javax.swing.JMenu jMenu98;
    private javax.swing.JMenu jMenu99;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar13;
    private javax.swing.JMenuBar jMenuBar14;
    private javax.swing.JMenuBar jMenuBar15;
    private javax.swing.JMenuBar jMenuBar16;
    private javax.swing.JMenuBar jMenuBar17;
    private javax.swing.JMenuBar jMenuBar18;
    private javax.swing.JMenuBar jMenuBar19;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar20;
    private javax.swing.JMenuBar jMenuBar21;
    private javax.swing.JMenuBar jMenuBar22;
    private javax.swing.JMenuBar jMenuBar23;
    private javax.swing.JMenuBar jMenuBar24;
    private javax.swing.JMenuBar jMenuBar25;
    private javax.swing.JMenuBar jMenuBar26;
    private javax.swing.JMenuBar jMenuBar27;
    private javax.swing.JMenuBar jMenuBar28;
    private javax.swing.JMenuBar jMenuBar29;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar30;
    private javax.swing.JMenuBar jMenuBar31;
    private javax.swing.JMenuBar jMenuBar32;
    private javax.swing.JMenuBar jMenuBar33;
    private javax.swing.JMenuBar jMenuBar34;
    private javax.swing.JMenuBar jMenuBar35;
    private javax.swing.JMenuBar jMenuBar36;
    private javax.swing.JMenuBar jMenuBar37;
    private javax.swing.JMenuBar jMenuBar38;
    private javax.swing.JMenuBar jMenuBar39;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar40;
    private javax.swing.JMenuBar jMenuBar41;
    private javax.swing.JMenuBar jMenuBar42;
    private javax.swing.JMenuBar jMenuBar43;
    private javax.swing.JMenuBar jMenuBar44;
    private javax.swing.JMenuBar jMenuBar45;
    private javax.swing.JMenuBar jMenuBar46;
    private javax.swing.JMenuBar jMenuBar47;
    private javax.swing.JMenuBar jMenuBar48;
    private javax.swing.JMenuBar jMenuBar49;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar50;
    private javax.swing.JMenuBar jMenuBar51;
    private javax.swing.JMenuBar jMenuBar52;
    private javax.swing.JMenuBar jMenuBar53;
    private javax.swing.JMenuBar jMenuBar54;
    private javax.swing.JMenuBar jMenuBar55;
    private javax.swing.JMenuBar jMenuBar56;
    private javax.swing.JMenuBar jMenuBar57;
    private javax.swing.JMenuBar jMenuBar58;
    private javax.swing.JMenuBar jMenuBar59;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar60;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mniAnggota;
    private javax.swing.JMenuItem mniCari;
    private javax.swing.JMenuItem mniEdit;
    private javax.swing.JMenuItem mniHapus;
    private javax.swing.JMenuItem mniKoleksi;
    private javax.swing.JMenuItem mniPinjam;
    private javax.swing.JMenuItem mniSimpan;
    private javax.swing.JMenuItem mniUtama;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JPanel pnlAnggota;
    private javax.swing.JTable tblAnggota;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTtl;
    // End of variables declaration//GEN-END:variables
}
