
package eperpus;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NRSS
 */
public class Koleksi extends javax.swing.JFrame {
private static Connection koneksi; //Koneksi
    /**
     * Creates new form Koleksi
     */
public void tampilkandata() {
    
        DefaultTableModel tabelkoleksi = new DefaultTableModel();
        tabelkoleksi.addColumn("Kode Buku");
        tabelkoleksi.addColumn("Judul Buku");
        tabelkoleksi.addColumn("Pengarang");
        tabelkoleksi.addColumn("Penerbit");
        tabelkoleksi.addColumn("Stok");
        
        try {
            buka_koneksi();
            String sql = "select * from koleksi";
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelkoleksi.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
           tblKoleksi.setModel(tabelkoleksi);
        } catch (SQLException e) {
        }

    }
    public Koleksi() {
        initComponents();
         this.setLocationRelativeTo(this);
    }
        private static Connection buka_koneksi() {
        if (koneksi==null) {
            try {

                String url="jdbc:mysql://localhost:3306/eperpus"; //nama database belajar
                String user="root"; //user mysql
                String password=""; //password mysql

                koneksi=DriverManager.getConnection(url,user,password);
                
            }catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
     return koneksi;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlKoleksi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKoleksi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mniAnggota = new javax.swing.JMenuItem();
        mniKoleksi = new javax.swing.JMenuItem();
        mniPinjam = new javax.swing.JMenuItem();
        mniUtama = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniSimpan = new javax.swing.JMenuItem();
        mniEdit = new javax.swing.JMenuItem();
        mniCari = new javax.swing.JMenuItem();
        mniHapus = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-PERPUS");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlKoleksi.setBackground(new java.awt.Color(203, 180, 135));

        jLabel8.setFont(new java.awt.Font("Lato Black", 1, 36)); // NOI18N
        jLabel8.setText("FORM KOLEKSI BUKU");

        jLabel1.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel1.setText("Kode Buku");

        jLabel2.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel2.setText("Judul Buku");

        jLabel3.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel3.setText("Nama Pengarang");

        jLabel4.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel4.setText("Nama Penerbit");

        jLabel5.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah Stok");

        txtKode.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtJudul.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtPengarang.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtPenerbit.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        txtStok.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N

        btnSimpan.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Lato Heavy", 0, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblKoleksi.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N
        tblKoleksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Pengarang", "Penerbit", "Stok"
            }
        ));
        tblKoleksi.setEnabled(false);
        jScrollPane2.setViewportView(tblKoleksi);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo1.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lato Heavy", 0, 8)); // NOI18N
        jLabel7.setText("(Kode berupa angka)");

        javax.swing.GroupLayout pnlKoleksiLayout = new javax.swing.GroupLayout(pnlKoleksi);
        pnlKoleksi.setLayout(pnlKoleksiLayout);
        pnlKoleksiLayout.setHorizontalGroup(
            pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKoleksiLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKoleksiLayout.createSequentialGroup()
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlKoleksiLayout.createSequentialGroup()
                                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlKoleksiLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPengarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtKode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlKoleksiLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlKoleksiLayout.createSequentialGroup()
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKoleksiLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKoleksiLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(236, 236, 236)
                        .addComponent(jLabel6)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlKoleksiLayout.setVerticalGroup(
            pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKoleksiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKoleksiLayout.createSequentialGroup()
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKoleksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        mnuMenu.setText("MENU");
        mnuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuActionPerformed(evt);
            }
        });

        mniAnggota.setText("Anggota");
        mniAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAnggotaActionPerformed(evt);
            }
        });
        mnuMenu.add(mniAnggota);

        mniKoleksi.setText("Koleksi Buku");
        mniKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKoleksiActionPerformed(evt);
            }
        });
        mnuMenu.add(mniKoleksi);

        mniPinjam.setText("Peminjaman");
        mniPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPinjamActionPerformed(evt);
            }
        });
        mnuMenu.add(mniPinjam);

        mniUtama.setText("Utama");
        mniUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUtamaActionPerformed(evt);
            }
        });
        mnuMenu.add(mniUtama);

        jMenuBar1.add(mnuMenu);

        mnuHelp.setText("HELP");

        mniSimpan.setText("Simpan");
        mniSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSimpanActionPerformed(evt);
            }
        });
        mnuHelp.add(mniSimpan);

        mniEdit.setText("Edit");
        mniEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditActionPerformed(evt);
            }
        });
        mnuHelp.add(mniEdit);

        mniCari.setText("Cari");
        mniCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCariActionPerformed(evt);
            }
        });
        mnuHelp.add(mniCari);

        mniHapus.setText("Hapus");
        mniHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHapusActionPerformed(evt);
            }
        });
        mnuHelp.add(mniHapus);

        jMenuBar1.add(mnuHelp);

        mnuAbout.setText("ABOUT");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAnggotaActionPerformed
        // TODO add your handling code here:
          new Anggota().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniAnggotaActionPerformed

    private void mniKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKoleksiActionPerformed
        // TODO add your handling code here:
         new Koleksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniKoleksiActionPerformed

    private void mniPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPinjamActionPerformed
        // TODO add your handling code here:
          new Pinjam().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniPinjamActionPerformed

    private void mnuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mnuMenuActionPerformed

    private void mniUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUtamaActionPerformed
        // TODO add your handling code here:
          new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_mniUtamaActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if(txtKode.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtKode.requestFocus();
          }
        else{
        DefaultTableModel tabelkol = new DefaultTableModel();
        tabelkol.addColumn("Kode Buku");
        tabelkol.addColumn("Judul Buku");
        tabelkol.addColumn("Pengarang");
        tabelkol.addColumn("Penerbit");
        tabelkol.addColumn("Stok");
        
        try {
            buka_koneksi();
            String sql = "Select * from koleksi where kode like '%" +txtKode.getText()+
                    "%'" +"or judul like '%" + txtKode.getText() + "%'"; 
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            
               txtKode.setText("");
               txtJudul.setText("");
               txtPengarang.setText("");
               txtPenerbit.setText("");
               txtStok.setText("");
               txtKode.requestFocus();
            
            btnHapus.setEnabled(true);
            btnEdit.setEnabled(true);
           
            while (res.next()) {
                tabelkol.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),
                    res.getString(4),res.getString(5)});
            }
           tblKoleksi.setModel(tabelkol);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan "+e);
        }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(txtKode.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text Kode Kosong","Informasi",1);
              txtKode.requestFocus();
          }
          else{
          
        Connection c=buka_koneksi();
         String sqlkode="Delete from koleksi "+ "Where kode='"+this.txtKode.getText()+"'";
         String sql="Delete from stok "+ "Where kode='"+this.txtKode.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
               p.executeUpdate();
               p.close();

               txtKode.setText("");
               txtJudul.setText("");
               txtPengarang.setText("");
               txtPenerbit.setText("");
               txtStok.setText("");
               txtKode.requestFocus();
               
               tampilkandata();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if((txtKode.getText().equals(""))||(txtJudul.getText().equals(""))||
                 (txtPengarang.getText().equals(""))||(txtPenerbit.getText().equals(""))
                 ||(txtStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
        else{
        Connection c=buka_koneksi(); 
        String sqlkode="Update koleksi SET judul='"+this.txtJudul.getText()+"'," + "pengarang='"+this.txtPengarang.getText()+"',"
                +"penerbit='"+this.txtPenerbit.getText()+"',"+"stok='"+this.txtStok.getText()+"'"+"Where kode='"+this.txtKode.getText()+"'";
        String sql="Update stok SET jumlah='"+this.txtStok.getText()+"'"+"Where kode='"+this.txtKode.getText()+"'";   
        try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
               p.executeUpdate();
               p.close();
               JOptionPane.showMessageDialog(this, "Edit Berhasil","Informasi",1);
               txtKode.setText("");
               txtJudul.setText("");
               txtPengarang.setText("");
               txtPenerbit.setText("");
               txtStok.setText("");
               txtKode.requestFocus();
               
               tampilkandata();
            }
             catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if((txtKode.getText().equals(""))||(txtJudul.getText().equals(""))||
                 (txtPengarang.getText().equals(""))||(txtPenerbit.getText().equals(""))
                 ||(txtStok.getText().equals("")))
            {
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
         else{
        
        Connection c=buka_koneksi(); //panggil function koneksi
         String sqlkode="Insert into koleksi(kode,judul,pengarang,penerbit,stok) values ('"+this.txtKode.getText()+"',"
                     + "'"+this.txtJudul.getText()+"',"+ "'"+this.txtPengarang.getText()+"',"
                 +"'"+this.txtPenerbit.getText()+"',"+"'"+this.txtStok.getText()+"')";
         
         String sql="Insert into stok(kode,jumlah) values ('"+this.txtKode.getText()+"',"+"'"+this.txtStok.getText()+"')";
                 
            try { //jalankan query tersebut
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               PreparedStatement p3=(PreparedStatement) c.prepareStatement(sql);
               p3.executeUpdate();
               p3.close();
               txtKode.setText("");
               txtJudul.setText("");
               txtPengarang.setText("");
               txtPenerbit.setText("");
               txtStok.setText("");
               btnEdit.setEnabled(true);
               btnHapus.setEnabled(true);
               txtKode.requestFocus();
               tampilkandata();
               
               JOptionPane.showMessageDialog(this, "Simpan Berhasil","Informasi",1);
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
           
               btnEdit.setEnabled(true);
               btnHapus.setEnabled(true);
               txtKode.requestFocus();
               tampilkandata();
               
            }
         }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tampilkandata();
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        txtKode.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void mniSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSimpanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi semua kolom data agar dapat menyimpan data.");
    }//GEN-LAST:event_mniSimpanActionPerformed

    private void mniEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi Kode buku dan masukan semua data yang ingin diedit.");
    }//GEN-LAST:event_mniEditActionPerformed

    private void mniCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCariActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan Kode buku atau judul buku untuk mencari data."
            + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniCariActionPerformed

    private void mniHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHapusActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan Kode buku yang ingin dihapus."
            + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniHapusActionPerformed

    private void mnuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Aplikasi ini dibuat untuk memudahkan admin untuk mendata anggota, inventaris buku, dan peminjaman buku perpustakaan."
            + "\nSemoga bermanfaat -NRSS"+"\n");
    }//GEN-LAST:event_mnuAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Koleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Koleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Koleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Koleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Koleksi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mniAnggota;
    private javax.swing.JMenuItem mniCari;
    private javax.swing.JMenuItem mniEdit;
    private javax.swing.JMenuItem mniHapus;
    private javax.swing.JMenuItem mniKoleksi;
    private javax.swing.JMenuItem mniPinjam;
    private javax.swing.JMenuItem mniSimpan;
    private javax.swing.JMenuItem mniUtama;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMenu;
    private javax.swing.JPanel pnlKoleksi;
    private javax.swing.JTable tblKoleksi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
