
package eperpus;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NRSS
 */
public class Pinjam extends javax.swing.JFrame {
private static Connection koneksi; //Koneksi

    /**
     * Creates new form Pinjam
     */
  public void tampilkandata() {
    
        DefaultTableModel tabelpinjam = new DefaultTableModel();
        tabelpinjam.addColumn("ID");
        tabelpinjam.addColumn("Kode");
        tabelpinjam.addColumn("Tangal Pinjam");
        tabelpinjam.addColumn("Tanggal Kembali");
        tabelpinjam.addColumn("Denda");
        
        try {
            buka_koneksi();
            String sql = "select * from pinjam";
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelpinjam.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
           table3.setModel(tabelpinjam);
        } catch (Exception e) {
        }

    }
   
    
    public Pinjam() {
        initComponents();
         this.setLocationRelativeTo(this);
    }
 private static Connection buka_koneksi() {
 if (koneksi==null) {
            try {

                String url="jdbc:mysql://localhost:3306/eperpus"; //nama database 
                String user="root"; //user mysql
                String password=""; //password mysql
               
                koneksi=DriverManager.getConnection(url,user,password);
                
            }catch (SQLException t) {
                JOptionPane.showMessageDialog(null,"Terjadi kesalahan "+t.getMessage());
            }
        }
     return koneksi;
     
 }
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        pnlPinjam = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPinjam = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniSimpan = new javax.swing.JMenuItem();
        mniEdit = new javax.swing.JMenuItem();
        mniCari = new javax.swing.JMenuItem();
        mniHapus = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-PERPUS");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pnlPinjam.setBackground(new java.awt.Color(203, 180, 135));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lato Heavy", 1, 8)); // NOI18N
        jLabel10.setText("YYYY-MM-DD");

        jLabel11.setFont(new java.awt.Font("Lato Heavy", 1, 8)); // NOI18N
        jLabel11.setText("YYYY-MM-DD");

        btnCari.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cari.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lato Heavy", 1, 36)); // NOI18N
        jLabel12.setText("FORM PEMINJAMAN");

        jLabel1.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel1.setText("ID Anggota");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel2.setText("Kode Buku");

        jLabel3.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel3.setText("Tanggal Pinjam");

        jLabel4.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel4.setText("Tanggal Kembali");

        jLabel5.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel5.setText("Denda");

        table3.setFont(new java.awt.Font("Lato Medium", 0, 12)); // NOI18N
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode", "Tanggal Pinjam", "Tanggal Kembali", "Denda"
            }
        ));
        table3.setEnabled(false);
        jScrollPane4.setViewportView(table3);

        jLabel6.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel6.setText("Nama Anggota");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Lato Heavy", 1, 12)); // NOI18N
        jLabel7.setText("Judul");
        jLabel7.setToolTipText("");

        txtNama.setEnabled(false);

        txtJudul.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Lato Heavy", 1, 8)); // NOI18N
        jLabel13.setText("(ID berupa angka)");

        jLabel14.setFont(new java.awt.Font("Lato Heavy", 1, 8)); // NOI18N
        jLabel14.setText("(Kode berupa angka)");

        jLabel8.setFont(new java.awt.Font("Lato", 1, 8)); // NOI18N
        jLabel8.setText("(Tekan ENTER)");

        jLabel9.setFont(new java.awt.Font("Lato", 1, 8)); // NOI18N
        jLabel9.setText("(Tekan ENTER)");

        javax.swing.GroupLayout pnlPinjamLayout = new javax.swing.GroupLayout(pnlPinjam);
        pnlPinjam.setLayout(pnlPinjamLayout);
        pnlPinjamLayout.setHorizontalGroup(
            pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPinjamLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPinjamLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPinjamLayout.createSequentialGroup()
                        .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(33, 33, 33)
                        .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPinjamLayout.createSequentialGroup()
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txtDenda)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txtKembali)
                                    .addComponent(txtKode))
                                .addGap(34, 34, 34)
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(20, 20, 20)
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPinjamLayout.createSequentialGroup()
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(66, 66, 66))
        );
        pnlPinjamLayout.setVerticalGroup(
            pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPinjamLayout.createSequentialGroup()
                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPinjamLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(pnlPinjamLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPinjamLayout.createSequentialGroup()
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPinjamLayout.createSequentialGroup()
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPinjamLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(pnlPinjamLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPinjamLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenu1.setText("MENU");

        jMenuItem1.setText("Anggota");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Koleksi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Peminjaman");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Utama");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        mnuHelp.setText("HELP");

        mniSimpan.setText("Simpan");
        mniSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSimpanActionPerformed(evt);
            }
        });
        mnuHelp.add(mniSimpan);

        mniEdit.setText("Edit");
        mniEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditActionPerformed(evt);
            }
        });
        mnuHelp.add(mniEdit);

        mniCari.setText("Cari");
        mniCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCariActionPerformed(evt);
            }
        });
        mnuHelp.add(mniCari);

        mniHapus.setText("Hapus");
        mniHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHapusActionPerformed(evt);
            }
        });
        mnuHelp.add(mniHapus);

        jMenuBar1.add(mnuHelp);

        mnuAbout.setText("ABOUT");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
new Pinjam().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
new Koleksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
new Anggota().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampilkandata();
        txtNama.setEnabled(false);
        txtJudul.setEnabled(false);
        txtId.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void mniSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSimpanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi semua kolom data agar dapat menyimpan data.");
    }//GEN-LAST:event_mniSimpanActionPerformed

    private void mniEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Isi ID anggota, kode buku dan masukan semua data yang ingin diedit.");
    }//GEN-LAST:event_mniEditActionPerformed

    private void mniCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCariActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan ID anggota untuk mencari data peminjaman."
            + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniCariActionPerformed

    private void mniHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHapusActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Petunjuk: Masukan ID anggota untuk menghapus data peminjaman."
            + "\nTidak perlu mengisi semua kolom.");
    }//GEN-LAST:event_mniHapusActionPerformed

    private void mnuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Aplikasi ini dibuat untuk memudahkan admin untuk mendata anggota, inventaris buku, dan peminjaman buku perpustakaan."
            + "\nSemoga bermanfaat -NRSS"+"\n");
    }//GEN-LAST:event_mnuAboutMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if((txtId.getText().equals(""))||(txtKode.getText().equals(""))||(txtJudul.getText().equals(""))
                 ||(txtPinjam.getText().equals(""))||(txtKembali.getText().equals(""))||(txtDenda.getText().equals("")))
            {
                JOptionPane.showMessageDialog(this, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
        else{
        Connection c=buka_koneksi(); 
        String sqlkode="Update pinjam SET kode='"+this.txtKode.getText()+"'," + "tgl_Pinjam='"+this.txtPinjam.getText()+"',"
                +"tgl_Kembali='"+this.txtKembali.getText()+"',"+"denda='"+this.txtDenda.getText()+"'"+"Where id='"+this.txtId.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               JOptionPane.showMessageDialog(this, "Edit Berhasil","Informasi",1);
               txtId.setText("");
               txtNama.setText("");
               txtPinjam.setText("");
               txtKembali.setText("");
               txtKode.setText("");
               txtJudul.setText("");
               txtDenda.setText("");
               txtId.requestFocus();
               txtId.setEnabled(true);
               txtKode.setEnabled(true);

               tampilkandata();
            }
             catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text Id Kosong","Informasi",1);
              txtId.requestFocus();
          }
          else{
          
        Connection c=buka_koneksi();
         String sqlkode="Delete from pinjam "+ "Where id='"+this.txtId.getText()+"'";
            try {
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               
                txtId.setText("");
                txtNama.setText("");
                txtKode.setText("");
                txtJudul.setText("");
                txtPinjam.setText("");
                txtKembali.setText("");
                txtDenda.setText("");
                txtId.setEnabled(true);
                txtKode.setEnabled(true);
                txtId.requestFocus();
               tampilkandata();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
          }
        else{
        DefaultTableModel tabelpinjam = new DefaultTableModel();
        tabelpinjam.addColumn("ID");
        tabelpinjam.addColumn("Kode");
        tabelpinjam.addColumn("Tanggal Pinjam");
        tabelpinjam.addColumn("Tanggal Kembali");
        tabelpinjam.addColumn("Denda");
        
        try {
            buka_koneksi();
            String sql = "select * from pinjam where id="+txtId.getText();
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelpinjam.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
                table3.setModel(tabelpinjam);
                txtId.setText("");
                txtNama.setText("");
                txtKode.setText("");
                txtJudul.setText("");
                txtPinjam.setText("");
                txtKembali.setText("");
                txtDenda.setText("");
                txtId.setEnabled(true);
                txtKode.setEnabled(true);
                txtId.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan "+e);
        }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if((txtId.getText().equals(""))||(txtNama.getText().equals(""))||(txtKode.getText().equals(""))||(txtJudul.getText().equals(""))
                 ||(txtPinjam.getText().equals(""))||(txtKembali.getText().equals(""))||(txtDenda.getText().equals("")))
            {
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
            }
            else 
            {
                Connection c=buka_koneksi(); //panggil function koneksi
                String sqlkode="Insert into pinjam(id,kode,tgl_pinjam,tgl_kembali,denda) values ('"+this.txtId.getText()+"',"
                     + "'"+this.txtKode.getText()+"',"+ "'"+this.txtPinjam.getText()+"',"+"'"+this.txtKembali.getText()+"',"
                 +"'"+this.txtDenda.getText()+"')";
            try { //jalankan query tersebut
               PreparedStatement p2=(PreparedStatement) c.prepareStatement(sqlkode);
               p2.executeUpdate();
               p2.close();
               
               //tampilkan data
                tampilkandata();
                JOptionPane.showMessageDialog(this, "Simpan Berhasil","Informasi",1);
                
                txtId.setText("");
                txtNama.setText("");
                txtKode.setText("");
                txtJudul.setText("");
                txtPinjam.setText("");
                txtKembali.setText("");
                txtDenda.setText("");
                txtId.setEnabled(true);
                txtKode.setEnabled(true);
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
              
                
                txtId.requestFocus();
           
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
           txtId.setText("");
                
                txtId.setEnabled(true);
                txtKode.setEnabled(true);
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
              txtNama.setText("");
              txtJudul.setText("");
              txtKode.setText("");
                
                txtId.requestFocus();
  
            }
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
          }
        else{
        try {
            buka_koneksi();
            String sql = "Select nama from anggota where id =" +txtId.getText(); 
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            
            while (res.next()) {
            txtNama.setText(res.getString("Nama"));
            }
        }
          catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan ");
        }
         }
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
        if(txtKode.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text Kode Kosong","Informasi",1);
              txtKode.requestFocus();
          }
        else{
        try {
            buka_koneksi();
            String sql = "Select judul from koleksi where kode =" +txtKode.getText(); 
            Statement stat = koneksi.createStatement();
            ResultSet res=stat.executeQuery(sql);
            
            while (res.next()) {
            txtJudul.setText(res.getString("Judul"));
            txtKode.setEnabled(false);
            }
        }
          catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan ");
        }
         }
    }//GEN-LAST:event_txtKodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mniCari;
    private javax.swing.JMenuItem mniEdit;
    private javax.swing.JMenuItem mniHapus;
    private javax.swing.JMenuItem mniSimpan;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JPanel pnlPinjam;
    private javax.swing.JTable table3;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPinjam;
    // End of variables declaration//GEN-END:variables
}
